### ISSUE TITLE
добавить в шапку ссылку на общую ленту

### ISSUE THREAD

**Issue by ameliaailema** [GoodKitties/dybr-client#103]
сейчас в шапку можно добавить только одну свою кнопку. теоретически юзеры могут сами потратить ее на ссылку на общую ленту, однако логичнее было бы, чтобы такая кнопка была сразу.

сейчас, чтобы попасть в общую ленту, нужно сначала перейти на главную, а оттуда уже в общую ленту.

**Comment by simoroshka** [comment]
мы не будем этого делать, у нас запланированы другие вещи для добавления в шапку, и мы не хотим ее перегружать. И не хотим сначала добавлять кнопку, а потом убирать. 
По мере развития сайта важность общей ленты снизится, она не будет больше главным хабом. Поэтому сейчас предлагаем ставить ее на быструю кнопку.
