### ISSUE TITLE
адаптив: закрепленное меню редактора должно быть самым верхним элементом

### ISSUE THREAD

**Issue by ameliaailema** [GoodKitties/dybr-client#120]
**Описание бага**
на телефоне в браузере при написании поста/комментария, при промотке закрепленное меню располагается так, что над ним видно кусок текстового поля

на видео: https://drive.google.com/file/d/1CCNIQ1H46McGRPxQVUJAu7YQJ0mcxE57/view?usp=sharing

**Как повторить**
Шаги для появления бага:
1. открыть форму поста/комментария в браузере на телефоне
2. ввести текст
3. промотать вниз до кнопки "отправить"

**Ожидаемое поведение**

если закрепляем меню, то так, чтобы оно всегда было в верхней части страницы, а не как сейчас, когда над ним показывается частично перекрытый текст https://www.screencast.com/t/cVyAeWGQVwu

**Comment by simoroshka** [comment]
это не баг, это фича. Без нее очень часто создавалась ситуация, что
закрепленная панель перекрывала первые строки и казалось, что либо там
ничего нет, либо курсор куда-то пропал и ничего не печатается.
