### ISSUE TITLE
на телефоне в браузере не должны деформироваться картинки 

### ISSUE THREAD

**Issue by ameliaailema** [GoodKitties/dybr-client#121]
**Описание бага**
при просмотре постов с телефона в браузере некоторые картинки деформируются. на десктопе все в порядке

**Как повторить**
Шаги для появления бага:
1. открыть пост с телефона в браузере

**Ожидаемое поведение**
картинки не деформируются

**Скриншоты**
скрин с телефона https://www.screencast.com/t/QQ4p9fhyx
скрин с десктопа https://www.screencast.com/t/jYxkwEw08bt
ссылка на пост https://dybr.ru/blog/kovert/1751

**Моё окружение:**
 - Операционная система: Android 6.0
 - Браузер Chrome
 - Версия 69

**Comment by simoroshka** [comment]
если автор ставит inline height, то наши варианты весьма ограничены. Их два. Первый - вообще не добавлять мобильных стилей к картинкам (и они тогда вылезают за пределы экрана, что еще хуже, чем ужимание). Второй, который сейчас - применять ширину 100%. Можно только еще добавить принудительно высоту auto с определенного размера экрана, но всё равно будут случаи, когда картинка будет странно масштабироваться.

**Comment by ameliaailema** [comment]
может, скролл делать? нечто похожее, кажется, было на даери. не блеск, но лучше, чем ломать верстку или деформировать картинку
