### ISSUE TITLE
Теряется пропорциональность изображения при установке высоты

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/dybr-client#131]
**Описание бага и как повторить**
Теряется пропорциональность изображения, если задать высоту, при которой ширина изображения будет превышать ширину дневника.

Шаги для появления бага:
1. Добавить в запись изображение и задать ему высоту, при которой соответствующая ширина будет превышать ширину дневника.

**Ожидаемое поведение**
Изображение будет принимать не выставленную высоту, а высоту, соответствующую максимальной возможной ширине, и таким образом сохранять пропорции.

**Скриншоты**
При установке "ширина [800px], высота [пусто]" изображение адекватно масштабируется до ширины дневника (600 минус поля).
![image](https://user-images.githubusercontent.com/37691742/48961156-6c358080-ef83-11e8-976b-7eadcd76c26a.png)
При установке "ширина [пусто], высота [800px]" изображение теряет пропорциональность ширины и высоты, т.е. ширина задаётся по ширине дневника, а высота - по установкам изображения.
![image](https://user-images.githubusercontent.com/37691742/48961380-e87c9380-ef84-11e8-90fd-70724cfd17fe.png)

**Дополнительная информация (если применимо)**
Поехавшее изображение легко заметить в своём дневнике, но в случае, даже если в своём дневнике всё выглядит адекватно, остаётся вариант, при котором в избранном человека с более узким дизайном картинку может перекосить, и автор об этом не узнает.

**Comment by simoroshka** [comment]
это особенности css, не знаю, можем ли мы что-то по этому поводу сделать.

**Comment by PandeRoma** [comment]
Хм. В редакторе по умолчанию стоит "ширина столько-то пикселей", мне и в голову не приходило, что можно ставить в процентах.
Может, тогда запретить выставлять высоту? Или высоту без ширины? (Как-нибудь сделать так, чтобы автоматически из высоты высчитывалась ширина, и уже по ширине задавался масштаб?) А то если кто-то возьмётся выставлять размеры картинок по высоте, на мобильных точно всё поедет сильно. А потом кто-нибудь ещё и скажет, что "у вас сайт плохой, картинки мне все поломал".

**Comment by simoroshka** [comment]
Это сложный вопрос в целом - как сделать так, чтобы и у пользователя была
свобода действий, и чтобы при этом работало нормально в разных дизайнах и
на мобильных. Пока что у меня одно возможное решение придумалось: запретить
выставлять высоту картинки (удалять ее из кода), потому что браузер скейлит
нормально только при выставленной ширине, но не высоте... и оставить в
глобальных стилях max-width 100%, чтобы картинки не в любом случае не
вылезали за пределы блоков, что бы юзер не выставил.
Другой вариант: преобразовывать картинки в блоки с фоном, к которым уже
применяется высота-ширина. Тогда будет больше опций, как именно картинка
будет отображаться: contain, cover, stretch, т.д, как в шапке дневника. Но
это замороченно в реализации и, имхо, неочевидно для пользователя.

**Comment by simoroshka** [comment]
сделала игнор установленной высоты, теперь нормально скейлится
