### ISSUE TITLE
Свой дизайн в чужом блоге при переходе из избранного

### ISSUE THREAD

**Issue by simoroshka** [GoodKitties/dybr-client#142]
**Описание бага и как повторить**
Открыть своё избранное. 
Перейти в запись из блога, в котором нет дизайна.
Блог будет в дизайне своего дневника. 
После перезагрузки страницы дизайн сбрасывается. 

**Ожидаемое поведение**
Чужой дневник всегда показывается в дизайне этого дневника.

**Comment by luarsoll** [comment]
Также если свой блог без дизайна, то если сначала зайти в чужой блог с дизайном, а потом в избранное, то избранное будет с дизайном чужого блога
