### ISSUE TITLE
Сабдомены для дневников

### ISSUE THREAD

**Issue by simoroshka** [GoodKitties/dybr-client#16]
reflexive.dybr.ru вместо dybr.ru/blog/reflexive
должно быть возможно в реакте, если разбивать url https://stackoverflow.com/questions/35658252/subdomain-in-react-router
плюс нужно настроить сервер? И прикрутить wildcard SSL

**Comment by Adonai** [comment]
Then we need validity check for blog slugs. They can't contain non-valid characters for domain names.
Should we bother with this, really? For now I think dybr.ru/<slug>/ is sufficient.
