### ISSUE TITLE
Тег br отображается в имейле с комментарием

### ISSUE THREAD

**Issue by bookdreamer** [GoodKitties/dybr-client#160]
Пришел имейл с комментарием к моему посту, а там тег <br> в явном виде.

![screenshot at 2019-01-15 12-02-02](https://user-images.githubusercontent.com/32674679/51173208-9ccbd380-18bd-11e9-9d42-114b57397e46.png)

В самом комментарии на сайте все нормально выглядит, обычный строка-отступ.

Google Chrome, Linux Mint

**Comment by bogolt** [comment]
пофиксил
