### ISSUE TITLE
Не работает удаление собственной записи из закладок

### ISSUE THREAD

**Issue by simoroshka** [GoodKitties/dybr-client#175]
**Описание бага и как повторить**
Если добавить свою же запись в закладки, то при просмотре со страницы закладок ее не получается удалить.
1. добавить свою запись в закладки
2. перейти на страницу закладок
3. открыть меню управления записью
4. нажать "удалить"
- ничего не происходит

**Ожидаемое поведение**
Запись удаляется как обычно.

**Comment by PandeRoma** [comment]
Если добавить себя в избранное - из ленты избранного тоже не работает удаление.
