### ISSUE TITLE
не получается читать текст под катом

### ISSUE THREAD

**Issue by trebushetms** [GoodKitties/dybr-client#179]
захожу в свой дневник, нажимаю на кнопку [MORE], чтобы увидеть текст, спрятанный под катом. выбрасывает на главную страницу

запись: https://dybr.ru/blog/trebuchet_ms/26381?page=1#

**Comment by simoroshka** [comment]
Это происходит если пытаться открыть кат как ссылку в новой вкладке. Нужно
просто нажать, оно раскроется на этой же странице.
