### ISSUE TITLE
Своя запись, закрытая от всех, не видна через избранное

### ISSUE THREAD

**Issue by PandeRoma** [GoodKitties/dybr-client#188]
**Описание бага и как повторить**
Своя запись, закрытая от всех, не видна через избранное.

Шаги для появления бага:
1. Добавить свой блог в избранное
2. Создать запись с настройками доступа "закрыта от всех"
3. Не увидеть эту запись в избранном

**Ожидаемое поведение**
Все свои записи будут видны в избранном при добавлении себя в избранное.

**Comment by bogolt** [comment]
сделано
