### ISSUE TITLE
При доб. таблица нулевой ширины

### ISSUE THREAD

**Issue by nkorobicina** [GoodKitties/dybr-client#19]
Если в запись вставить таблицу, то она нулевой ширины, см. скриншот ниже. Ее можно растянуть курсором, либо начать писать текст в ячейки, и тогда она начнет растягиваться по ширине текста.

 В демонстрации редактора таблица при добавлении сразу же растягивается на ширину текстовой области.

![- google chrome 2018-03-20 21 10 41](https://user-images.githubusercontent.com/16016497/37667256-6228ea1e-2c83-11e8-8070-cc38f6ca62e2.png)

**Comment by simoroshka** [comment]
Возникает ли всё ещё эта проблема? У меня встраивается на 100% ширины сейчас.

**Comment by nkorobicina** [comment]
Да, перестало воспроизводиться.
