### ISSUE TITLE
кнопки, которых не хватает в приложении

### ISSUE THREAD

**Issue by Balfor** [GoodKitties/dybr-client#196]
1. не достаёт кнопок **up & down** не только в дневнике или на главной странице, но и в комментариях.
неудобство: при переходе из вкладки "уведомления" к ответу, приходится долго листать вниз к окошку написания комментария, было бы лучше, если бы гиперссылка вела сразу к написанию ответа.
2. можно добавить кнопку **"очистить всё"** в поле ввода текста, т. к. зачастую случайно нажимаешь на чей-нибудь ник, а после машинально на отмену написания комментария, и он сохраняет один этот ник как черновик.
3. неудобство: при написании быстрого ответа без цитирования приходится запоминать, что писал пользователь, которому ты отвечаешь, или о чём шла речь в самом посте.
можно было бы сдвинуть панель инструментов текста чуть ниже, **приоткрыв обзор на пост**.
![Screenshot_20191213_215007_com kanedias dybr fair](https://user-images.githubusercontent.com/58857430/70819714-bb518c00-1df8-11ea-8bb2-5aba8e3ee51d.png)

**Comment by Balfor** [comment]
забыл укачать, что речь о приложении, но думаю, здесь итак понятно.

**Comment by Balfor** [comment]
забыл указать, что речь о приложении, но думаю, здесь итак понятно.

**Comment by simoroshka** [comment]
Перенисите, пожалуйста, сюда: https://github.com/GoodKitties/Fair/issues
