### ISSUE TITLE
некритичные ошибки, но тему бы посветлее, конечно

### ISSUE THREAD

**Issue by Balfor** [GoodKitties/dybr-client#197]
**приложение (последняя версия 1.13.4)**
1. не отображается дизайн, состоящий из одних стандартных настроек, у пользователя https://dybr.ru/profile/19954
дизайны остальных пользователей видно.
если не удастся устранить проблему, огромное пожелание разработчику: добавить светлую тему для приложения.
2. не ставятся абзацы, срабатывают только с пропуском одной строки.
![ош 1](https://user-images.githubusercontent.com/58857430/70818794-7167a680-1df6-11ea-83c0-81e31e039190.png)

**Comment by simoroshka** [comment]
Предложения и багрепорты по приложению вот тут живут, перенесите, пожалуйста: https://github.com/GoodKitties/Fair/issues
