### ISSUE TITLE
Ломается вёрстка таблицы в мобильном приложении

### ISSUE THREAD

**Issue by nyctalus-ms** [GoodKitties/dybr-client#207]
**Описание бага и как повторить**
1. Создать на десктопе запись с таблицей, добавить в таблицу изображение (см. код ниже).
2. Открыть страницу дневника или записи в мобильном приложении.

**Ожидаемое поведение**
Таблица отображается так же, как на десктопе ЛИБО отображюется изображение и текст из ячеек таблицы без самой таблицы.

**Фактическое поведение**
Вместо таблицы отображается ряд пунктирных линий, изображение не отображается, текст отображается.

**Скриншоты и код**
[code.txt](https://github.com/GoodKitties/dybr-client/files/4171803/code.txt)
![Screenshot_20200207-174121341](https://user-images.githubusercontent.com/60786386/74044939-fb8a5080-49dc-11ea-9f44-0bbb1de5c19d.jpg)
![2020-02-07 17-42-55 Дыбр - Mozilla Firefox](https://user-images.githubusercontent.com/60786386/74044946-fd541400-49dc-11ea-8fed-08fcb9606de1.png)

**Моё окружение:**
Десктоп:  win7 x86, FF 72.0.2
Смартфон: asus ze620kl, android 9, fair 1.14.3 (69)

**Дополнительная информация (если применимо)**
Ссылка на запись: https://dybr.ru/blog/nyctalus/1115095

**Comment by Kaned1as** [comment]
Дубликат https://github.com/GoodKitties/Fair/issues/10
