### ISSUE TITLE
Слетает форматирование стихотворений

### ISSUE THREAD

**Issue by raivoluz-linduine** [GoodKitties/dybr-client#219]
Здравствуйте! При отправке поста через слетают переходы на новую строку, и стихотворение отображается сплошным текстом. От того, через браузер (Firefox, Windows 10) или через приложение Fair с телефона отправляю, баг не зависит. 
[Вот запись в моём блоге](https://dybr.ru/blog/linduine/2096083? page=1#) и скриншоты. Набираю — всё в порядке, отправляю — форматирование слетает. 
![Screenshot_20200521-111004](https://user-images.githubusercontent.com/67045303/84874910-f1184b80-b08d-11ea-87b3-6e050c4eab05.jpg)
![Screenshot_20200521-111011](https://user-images.githubusercontent.com/67045303/84874942-fb3a4a00-b08d-11ea-99a7-e6b9c396836e.jpg)
Поправьте, пожалуйста.

**Comment by kullias** [comment]
это маркдаун, в нем новая строка - или ```<br>```, или два enter

**Comment by raivoluz-linduine** [comment]
> это маркдаун, в нем новая строка - или `<br>`, или два enter
Спасибо! Оно некрасиво выглядит, но лучше, чем никак.

**Comment by kullias** [comment]
кстати, есть еще вариант с двумя пробелами: https://gist.github.com/shaunlebron/746476e6e7a4d698b373 я не знаю как тут с его поддержкой, но это был бы самый крутой вариант
