### ISSUE TITLE
Оформление гиперссылок - визуально не отличается от обычного текста.

### ISSUE THREAD

**Issue by Bormotozavr** [GoodKitties/dybr-client#22]
При оформлении гиперссылки в редакторе был дополнительно установлен полужирный шрифт и зелёный цвет. В итоговой записи ссылка выглядит, как обычный текст. Подчёркивания так же нет. Понять, что это гиперссылка, можно только при наведении мыши и изменении курсора.
![default](https://user-images.githubusercontent.com/33678629/37773574-02dc47d2-2def-11e8-9f50-e78470df8823.png)

**Comment by simoroshka** [comment]
оформление текста стилями отключено
