### ISSUE TITLE
Все посты создаются от одного времени - 16:03.

### ISSUE THREAD

**Issue by Bormotozavr** [GoodKitties/dybr-client#28]
![default](https://user-images.githubusercontent.com/33678629/37774830-595e00f2-2df2-11e8-9654-e89c59d9004c.png)

**Comment by ameliaailema** [comment]
у меня то же самое, но на час позже (спб)

**Comment by ezhinka** [comment]
В моем случае час менялся, но :03 минуты неизменны. (т.е, запощенное приблизительно в 17:30 датируется 17:03, в 18:00 - как 18:03)

**Comment by simoroshka** [comment]
пофиксил, заливается) опечатка в коде
