### ISSUE TITLE
в Internet Explorer по наведению на шапку, она расползается на всю страницу и ломает верстку

### ISSUE THREAD

**Issue by ameliaailema** [GoodKitties/dybr-client#38]
мой любимый браузер не подводит никогда, проще один раз это увидеть
https://drive.google.com/file/d/1AUmde40NMKOJ8w4UOXPDGYhICu3cgE3H/view?usp=sharing

**Comment by simoroshka** [comment]
какая прелесть! )

**Comment by ameliaailema** [comment]
версия ие если что вот https://www.screencast.com/t/vMx9oM88o
система вин7 64

**Comment by PandeRoma** [comment]
Аналогично в Microsoft Edge 40.15063.674.0 Win10

**Comment by ameliaailema** [comment]
> мой любимый браузер не подводит никогда, проще один раз это увидеть
