### ISSUE TITLE
В постах не сохраняются изменения, внесенные в режиме кода. 

### ISSUE THREAD

**Issue by ameliaailema** [GoodKitties/dybr-client#40]
чтобы сохранить, надо при редактировании вернуться в режим визуального редактора, и только после этого публиковать пост
https://drive.google.com/file/d/1h_IYmmqFYDTdLhB4HmMAA4lAQwJEa_Ys/view?usp=sharing

**Comment by simoroshka** [comment]
Исправила для постов, форма комментариев чуть позже будет обновлена.
