### ISSUE TITLE
Непонятна система вставки изображений

### ISSUE THREAD

**Issue by BernardaMiele** [GoodKitties/dybr-client#43]
При выборе добавления изображений на верхней панели редактора предлагается только вставить ссылку на внешний ресурс, при этом при выборе быстрой вставки - наоборот, сразу открывается загрузка файла с компьютера. Если хостинг картинок не планируется, то куда они сохраняются?

**Comment by ameliaailema** [comment]
если загрузить картинку с компьютера и скопировать получившийся урл, то становится понятно, что картинки складываются на хостинг тех же ребят, что сделали визивиг, который используется. https://www.froala.com/

**Comment by BernardaMiele** [comment]
Ага. Но сколько они там храниться будут - неизвестно, может оказаться, что ненадёжно)

**Comment by Adonai** [comment]
Это тестовое хранилище картинок, фроаловское. Со временем, конечно, на своё перейдём
