### ISSUE TITLE
Неправильно работает more, если в тексте есть квадратные скобки

### ISSUE THREAD

**Issue by BernardaMiele** [GoodKitties/dybr-client#47]
Закрывающая квадратная скобка в тексте, который ставится вместо "читать дальше", срабатывает как конец тега, текст после неё уходит во вложение.

**Comment by simoroshka** [comment]
Вообще, он работает правильно, как ему и положено. :)

**Comment by BernardaMiele** [comment]
Факт :)) 
Значит, раз текстом его сделать сложно, просто будем учитывать)
