### ISSUE TITLE
Если ссылку убрать под more, она становится просто текстом

### ISSUE THREAD

**Issue by BernardaMiele** [GoodKitties/dybr-client#53]
При этом в обратную сторону - если сначала поставить тег more, а потом внутри него поставить ссылку - работает.

**Comment by Ellaire** [comment]
Не только ссылку. Если под море убрать список - он становится тоже сплошным текстом, а сам тэг море становится первым пунктом списка (т.е. если список был вида 1.... 2...3...,, то море будет идти после цифры 1 и содержать в себе все пункты списка сплошным текстом).
