### ISSUE TITLE
Открытие сторонних ссылок

### ISSUE THREAD

**Issue by luarsoll** [GoodKitties/dybr-client#55]
Вопрос спорный, но мне кажется, что удобнее, когда ссылки на сторонние ресурсы (например, на тлгрм-канал) открываются по умолчанию в новой вкладке (либо когда это можно настроить)

**Comment by simoroshka** [comment]
При встраивании ссылки через кнопку на панели редактора предлагается опция открытия в новом окне.

**Comment by luarsoll** [comment]
Ясно, спасибо
Я вставляла просто по Ctrl+V

**Comment by simoroshka** [comment]
Если кликнуть на нее, появится меню, третья кнопка дает то же окошко редактирования с галочкой.
