### ISSUE TITLE
Форматирование поля таблицы

### ISSUE THREAD

**Issue by luarsoll** [GoodKitties/dybr-client#56]
Если в поле таблицы есть только ссылка, то при установке курсора в это поле на мгновение промелькиевает тулбар настройки таблицы (вероятно, такой же, как при установке курсора в поле с просто текстом) и пропадает, появляется тулбар настройки ссылки

**Comment by simoroshka** [comment]
если поставить на ссылку, то появляется меню для ссылок. Если кликнуть в пустое место после ссылки, то появляется меню таблицы. Я бы сказала, что это так и должно быть.

**Comment by luarsoll** [comment]
У меня это работает только если после ссылки есть пробел. Если там пустое место за счет ширины таблицы, а не за счет пробелов, то получается меню ссылки.
Но неудобно не столько то, что я не могу отформатировать эту ячейку, а то, что при клике на пустое место после ссылки (если там нет пробелов) открывается один тулбар, сразу закрывается и открывается другой
ЗЫ. Браузер Firefox 57.0.2

**Comment by simoroshka** [comment]
окей, вижу теперь. Напишу разработчикам редактора, посмотрим, что скажут.
