### ISSUE TITLE
Странное поведение кнопок назад/вперед в Chrome

### ISSUE THREAD

**Issue by dkalinina** [GoodKitties/dybr-client#59]
Если из чужого блога перейти в свой по ссылке с хедера, а потом вернуться назад, то получаешь пустую страницу вместо предыдущего блога. Обратно в свой через "вперед" - снова пустая страница.
При переходе с записью в адресную строку такого не происходит и кнопки назад/вперед работают.
Версия 65.0.3325.181

![image](https://user-images.githubusercontent.com/14875152/37906288-3e612d7c-310a-11e8-92c4-a799d5b520d1.png)

**Comment by BernardaMiele** [comment]
Попробовала в яндексе (который тот же хром, знаю) - то же самое.

**Comment by PandeRoma** [comment]
В Опере то же самое.

**Comment by simoroshka** [comment]
это не зависит никак от браузера, это косяк в логике

**Comment by simoroshka** [comment]
Проблема не воспроизводится у меня, работает у вас или нет? Может быть оно исправилось, когда я исправляла другой баг? /скрестил пальцы/

**Comment by BernardaMiele** [comment]
Стало работать нормально. :)

**Comment by simoroshka** [comment]
Ура!
