### ISSUE TITLE
Дублирующие ссылки для профилей

### ISSUE THREAD

**Issue by dkalinina** [GoodKitties/dybr-client#61]
Для части ведущихся блогов имеются дублирующие их ссылки с номерами с ведущими нулями. Ведущих нулей может быть сколь угодно много. При этом номера могут 
- совпадать с оригинальным дневником https://dybr.ru/blog/00006
- совпадать с номером профиля https://dybr.ru/blog/00034
- не совпадать с ними https://dybr.ru/blog/00050

Каждый раз это номера от 0 до 7, т.е. 
006 (для блога 6,  автора 1),
013 (для блога 11, автора 16),
015 (для блога 13, автора 18),
032 - 037 (для блогов 26-31, авторов 32-37), 
040 - 047 (для блогов 32-39, авторов 38-45), 
050 - 057(для блогов 40-47, авторов 46-53), 
060 - 067(для блогов 48-55, авторов 54-61), 
070 - 077(для блогов 56-63, авторов 70-77).
Для блогов с 64(авторов с 78) дублирующих номеров не нашлось.

**Comment by Adonai** [comment]
Ха, это же октетная нотация :) ноль означает перевод в 8-ричную систему.

13<sup>8</sup> == 11<sup>10</sup>

**Comment by simoroshka** [comment]
весело) Сделаю приведение к инту для профилей, для блогов айди теперь не используется

**Comment by dkalinina** [comment]
Точняк! И шестнадцатеричная тоже пашет))))

**Comment by simoroshka** [comment]
веселые ссылки будут работать так: 0000032 ведет к профилю 32, 0x32 ведет к профилю 50. Good enough for me.
