### ISSUE TITLE
Невидимый дневник

### ISSUE THREAD

**Issue by dkalinina** [GoodKitties/dybr-client#62]
https://dybr.ru/blog/26
При загрузке на долю секунды отображаются название и имя автора, а затем остается пустая страница. У пользователя есть дневник https://dybr.ru/profile/32 

пысы: учитывая, что это Kanedias, вполне возможно, что там что-то тестится

**Comment by simoroshka** [comment]
У нас проблема с бэкендом, который почему-то возвращает пустые объекты для записей, к которым нет доступа (в данном случае - черновые).
