### ISSUE TITLE
Проблема при публикации записи с только заголовком 

### ISSUE THREAD

**Issue by Kot-vertolet** [GoodKitties/dybr-client#63]
При попытке сделать запись с надписью только в заголовке страница остается с записью "публикуем" и ничего далее не происходит 

Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://dybr.ru/static/js/main.734f1cf9.js
Source Map URL: main.734f1cf9.js.map[Learn More]

**Comment by simoroshka** [comment]
уже было
