### ISSUE TITLE
Слишком длинный заголовок 

### ISSUE THREAD

**Issue by Kot-vertolet** [GoodKitties/dybr-client#64]
Если писать загололок в одно слово, то он выходит за границы поля. Лимита на количество симболов в слове нет. 
![image](https://user-images.githubusercontent.com/38263917/38582757-7ba0df78-3d19-11e8-9a53-d2aab4e9cfd9.png)

**Comment by simoroshka** [comment]
лимита на количество символов в слове и не должно быть, должны быть авто-переносы, или скрывание. Но кто вообще кроме тестировщиков с этим столкнется?)
