### ISSUE TITLE
при переходе со страницы профиля в свой дневник  открывается 404

### ISSUE THREAD

**Issue by ameliaailema** [GoodKitties/dybr-client#74]
- идем в профиль
- нажимаем на название дневника. ожидается переход в дненвик
- в реальности получается пустая страница с урлом дневника
- при перезагрузке этой страницы откроется 404

**Comment by simoroshka** [comment]
не воспроизводится. Попробуй зайти на https://dybr.ru/errorlog и нажать серую кнопку, а потом зайти снова.

**Comment by PandeRoma** [comment]
У меня воспроизводится, но не каждый раз. Браузер Опера 53.0

**Comment by ameliaailema** [comment]
нажала серую кнопку, спустя несколько повторений все равно воспроизводится

**Comment by ameliaailema** [comment]
хром Версия 67.0.3396.87 (Официальная сборка), (64 бит)
вин10
