### ISSUE TITLE
пагинация не должна быть с учетом удаленных постов

### ISSUE THREAD

**Issue by ameliaailema** [GoodKitties/dybr-client#75]
на одной стр сейчас помещается 9 постов. если написать 10 постов, получится пагинация из 2 страниц. если удалить все посты на одной странице, пагинация не перестроится, и по-прежнему будет показывать страницу, на которой когда-то были эти удаленные посты (пустой, соответственно)
https://s8.hostingkartinok.com/uploads/images/2018/06/d047107958403b5e9d7c7502867bb2ce.png

**Comment by simoroshka** [comment]
а если зайти в дневник снова, пагинация обновляется?

**Comment by ameliaailema** [comment]
нет, но судя по всему это только со страницами, где были старые посты. старые страницы не пересчитываются, новые пересчитываются
http://www.youtube.com/watch?v=9idnALOYeLs

**Comment by simoroshka** [comment]
Пометка для себя: количество записей "сидит" на объекте блога, нужно сделать обновление счетчика на клиенте при успешном удалении записи, и перезагрузить страницу.
