### ISSUE TITLE
при авторизации браузер каждый раз предлагает сохранить логин и пароль

### ISSUE THREAD

**Issue by ameliaailema** [GoodKitties/dybr-client#83]
каждый раз как логинишься предлагает сохранить, даже если уже соглашались до этого.
судя по всему, данные не сохраняются и соответственно в форму не подставляются

**Comment by simoroshka** [comment]
не воспроизводится. Какой браузер?

**Comment by ameliaailema** [comment]
у меня с рабочего компа сейчас тоже не воспроизводится, вероятно что-то локальное
