### ISSUE TITLE
листание ленты

### ISSUE THREAD

**Issue by Sudo22** [GoodKitties/dybr-client#87]
После первых пяти страниц, дальше есть возможность переходить только о одной странице.
Это неудобно если нудное тебе будет в конце ленты.
<img width="1246" alt="2018-06-24 14 08 56" src="https://user-images.githubusercontent.com/40537447/41818462-4ddf8600-77b8-11e8-8516-08f817391b06.png">

**Comment by simoroshka** [comment]
в данном случае показывается только следующая страница, потому что бэкенд не возвращает общее количество записей. В недалеком будущем как минимум будет приделана сортировка в обратном порядке.
