### ISSUE TITLE
При отправке комментария к записи надо обновить страницу, чтобы он появился под записью.

### ISSUE THREAD

**Issue by Studiozus** [GoodKitties/dybr-client#89]
Без обновления страница как будто "зависает", окошко комментирования остается неактивным, кнопка "комментировать" превращается в кнопку "Публикуется", и ничего не происходит.
Если после этого обновить страницу, то видно, что комментарий опубликован и все вернулось в норму.

**Comment by Studiozus** [comment]
![comment 1](https://user-images.githubusercontent.com/37754084/43806902-aef12b7e-9aae-11e8-8a6c-88fabf91ce6f.png)

**Comment by simoroshka** [comment]
Повторяется ли сейчас эта ошибка?

**Comment by Studiozus** [comment]
Сейчас - нет, все работает отлично.
Спасибо!

С уважением
Шевелева Анастасия
8(964)5355224

2018-09-09 18:37 GMT+03:00 Anna Kruglaia <notifications@github.com>:

**Comment by simoroshka** [comment]
Ура!
