### ISSUE TITLE
Загрузка изображений для дизайна с диска

### ISSUE THREAD

**Issue by Reihoo** [GoodKitties/dybr-client#93]
При попытке загрузить изображение для фона/шапки с диска выдает "Что-то пошло не так во время загрузки, простите нас", при этом изображения ссылкой прекрасно встраиваются в дизайн.

**Comment by bogolt** [comment]
Должна была починится, как сможете попробуйте пожалуйста и скажите помогло или нет

**Comment by Reihoo** [comment]
Да, теперь все работает)
