### ISSUE TITLE
Затирается пробел в редакторе

### ISSUE THREAD

**Issue by Vkabaeva** [GoodKitties/dybr-client#94]
То ли баг редактора, то ли фича (кривая фича, если честно).

Браузер хром, версия 68.0.3440.106

**Шаги:**
1. Открыть форму создания нового поста
2. Ввести что-нибудь, например, слово "тест"
3. Ввести пробел.
4. Ввести еще один символ, например, "т"
5. Нажать backspace на клавиатуре

**Ожидается:**
Стирается только "т" (последний символ), пробел и предыдущее слово остаются.

**Фактически:**
Пробел так же стирается.
Другие символы удаляются по одному, такое поведение только с пробелом.

**Comment by simoroshka** [comment]
Это баг редактора, который они обещают исправить в следующей версии (2.8.6).

**Comment by simoroshka** [comment]
То, что они исправили, нам не помогло, поэтому выкатила свой фикс.
