### ISSUE TITLE
Проматывать выпадающий список с шрифтами до текущего выбранного шрифта

### ISSUE THREAD

**Issue by eriott** [GoodKitties/dybr-client#98]
**Описание бага**
Если выбрать какой-либо шрифт при редактировании дизайна, при последующем выборе шрифта выпадающий список открывается сначала, а не с выбранного шрифта. Это неудобно, когда тыкаешь разные шрифты и проверяешь, как смотрится.

**Как повторить**
Шаги для появления бага:
1. Начать редактировать дизайн
2. Нажать на шрифты
3. Выбрать в выпадающем списке шрифт подальше от начала
4. Нажать еще раз на выбор шрифта
5. Выпадающий список проскроллен к началу, а не к выбранному шрифту

**Ожидаемое поведение**
Выпадающий список должен быть проскроллен до текущего выбранного шрифта.

**Моё окружение:**
 - Операционная система: Linux
 - Браузер: Chrome
 - Версия браузера: 60.0.3112.113

**Comment by simoroshka** [comment]
Вроде бы последние изменения исправили это. Во всяком случае у меня в последней версии клиента этой проблемы нет. 
кстати, там есть функция фильтрации - можно начать писать и оно покажет нужную опцию

**Comment by eriott** [comment]
Точно, сейчас у меня этого тоже нет. Спасибо)
